name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t gurpreet/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true gurpreet/react-test npm test

      - run: docker build -t gurpreet/multi-client ./client
      - run: docker build -t gurpreet/multi-nginx ./nginx
      - run: docker build -t gurpreet/multi-server ./server
      - run: docker build -t gurpreet/multi-worker ./worker